# Generated by Django 5.2.9 on 2025-12-05 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('muscle_group_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('exercise_name', models.CharField(max_length=100)),
                ('exercise_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.exercisecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.exercise')),
                ('muscle_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_tracker.musclegroup')),
            ],
        ),
    ]
