# Generated by Django 5.2.9 on 2025-12-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisemusclegroup',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='exercisemusclegroup',
            old_name='muscle_group_id',
            new_name='muscle_group',
        ),
    ]
